# Generated by Django 4.1.4 on 2023-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_data',
            name='TeaSnacks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_data',
            name='breakfast',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_data',
            name='dinner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_data',
            name='lunch',
            field=models.IntegerField(),
        ),
    ]
