# Generated by Django 4.1.4 on 2023-01-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_review_delete_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_data', unique=True),
        ),
    ]
